import type { GuideHeading } from '@/lib/guide/nav'

/** Headings enrichis pour le sommaire de droite (scroll). */
export const DETAILED_HEADINGS: Record<string, GuideHeading[]> = {
  demarrer: [
    { id: 'a-propos', title: 'À propos' },
    { id: 'qui-fait-quoi', title: 'Qui fait quoi' },
    { id: 'parcours-complet', title: 'Le parcours d’un colis' },
    { id: 'comment-lire', title: 'Comment lire ce guide' },
  ],
  portails: [
    { id: 'landing', title: 'Depuis la page d’accueil' },
    { id: 'agence', title: 'Portail agence' },
    { id: 'antenne', title: 'Portail antenne' },
    { id: 'livreur', title: 'Portail livreur' },
    { id: 'suivi', title: 'Suivi public' },
    { id: 'inscription', title: 'Créer une agence (pas à pas)' },
  ],
  'depot-client': [
    { id: 'ouvrir', title: 'Ouvrir Accueil client' },
    { id: 'antenne', title: 'Choisir l’antenne' },
    { id: 'qr', title: 'Client avec téléphone (QR)' },
    { id: 'formulaire-qr', title: 'Formulaire côté client' },
    { id: 'walkin', title: 'Sans smartphone (comptoir)' },
    { id: 'demandes', title: 'Valider les demandes' },
    { id: 'modes', title: 'Domicile ou point relais' },
  ],
  'suivi-colis': [
    { id: 'ouvrir', title: 'Ouvrir le suivi' },
    { id: 'rechercher', title: 'Rechercher un colis' },
    { id: 'carte', title: 'Lire la fiche colis' },
    { id: 'statuts', title: 'Comprendre les statuts' },
    { id: 'hub', title: 'Retrait au hub' },
    { id: 'reclamation', title: 'Déposer une réclamation' },
  ],
  dashboard: [
    { id: 'ouvrir', title: 'Ouvrir le dashboard' },
    { id: 'haut', title: 'En-tête et raccourcis' },
    { id: 'alertes', title: 'Alertes hub' },
    { id: 'resume', title: 'Vue opérationnelle' },
    { id: 'actions', title: 'File « À traiter »' },
    { id: 'kpi', title: 'Cartes KPI' },
    { id: 'pipeline', title: 'Pipeline et hubs' },
  ],
  missions: [
    { id: 'ouvrir', title: 'Ouvrir Missions' },
    { id: 'liste', title: 'Liste, chips et recherche' },
    { id: 'creer', title: 'Créer une mission (formulaire)' },
    { id: 'statuts', title: 'Statuts et priorités' },
    { id: 'detail', title: 'Ouvrir le détail' },
    { id: 'assigner', title: 'Assigner / réassigner' },
    { id: 'actions-statut', title: 'Actions selon le statut' },
    { id: 'carte', title: 'Vue carte' },
  ],
  antennes: [
    { id: 'role', title: 'Rôle d’une antenne' },
    { id: 'ouvrir', title: 'Où les gérer' },
    { id: 'lien-ops', title: 'Lien avec les opérations' },
  ],
  flotte: [
    { id: 'ouvrir', title: 'Ouvrir Flotte' },
    { id: 'stats', title: 'Cartes de stats' },
    { id: 'tableau', title: 'Lire le tableau' },
    { id: 'ajouter', title: 'Ajouter un véhicule' },
    { id: 'assigner', title: 'Assigner un livreur' },
    { id: 'menu', title: 'Menu d’actions (⋯)' },
    { id: 'fleetman', title: 'FleetMan' },
  ],
  hubs: [
    { id: 'ouvrir', title: 'Ouvrir Hubs Relais' },
    { id: 'onglets', title: 'Onglets Hubs / Colis' },
    { id: 'creer', title: 'Nouveau hub' },
    { id: 'occupation', title: 'Occupation et alertes' },
    { id: 'depot-retrait', title: 'Déposer / retirer un colis' },
    { id: 'expiration', title: 'Colis expirés' },
  ],
  personnel: [
    { id: 'ouvrir', title: 'Ouvrir Personnel' },
    { id: 'onglets', title: 'Les cinq onglets' },
    { id: 'livreurs', title: 'Onglet Livreurs' },
    { id: 'contrats', title: 'Contrats' },
    { id: 'commissions-tab', title: 'Onglet Commissions' },
    { id: 'freelancers', title: 'Freelancers' },
  ],
  'vue-antenne': [
    { id: 'connexion', title: 'Se connecter' },
    { id: 'menu', title: 'Menu latéral' },
    { id: 'briefing', title: 'Dashboard antenne' },
    { id: 'dispatch', title: 'Dispatch et Mode Rush' },
    { id: 'gps', title: 'Personnel et GPS' },
    { id: 'hubs-locaux', title: 'Hubs de l’antenne' },
  ],
  'vue-livreur': [
    { id: 'connexion', title: 'Connexion et installation' },
    { id: 'nav', title: 'Barre du bas' },
    { id: 'disponibilite', title: 'Disponibilité' },
    { id: 'missions', title: 'Missions — enlèvement' },
    { id: 'pod', title: 'Confirmer la livraison (POD)' },
    { id: 'hub', title: 'Dépôt au hub' },
    { id: 'probleme', title: 'Signaler un problème' },
    { id: 'gains', title: 'Gains et contestation' },
    { id: 'hors-ligne', title: 'Mode hors ligne' },
  ],
  commissions: [
    { id: 'ou', title: 'Où les trouver' },
    { id: 'cycle', title: 'Le cycle' },
    { id: 'valider', title: 'Valider et payer (détail)' },
    { id: 'litige', title: 'Signaler un litige' },
    { id: 'livreur', title: 'Côté livreur' },
  ],
  facturation: [
    { id: 'ouvrir', title: 'Ouvrir Facturation' },
    { id: 'politiques', title: 'Politiques tarifaires' },
    { id: 'factures', title: 'Factures & Revenus' },
    { id: 'commissions-tab', title: 'Onglet Commissions' },
    { id: 'lien-missions', title: 'Lien avec les missions' },
  ],
  litiges: [
    { id: 'ouvrir', title: 'Ouvrir Litiges' },
    { id: 'clients', title: 'Litiges clients' },
    { id: 'incidents', title: 'Incidents livraison' },
    { id: 'origine', title: 'D’où viennent-ils' },
  ],
  parametres: [
    { id: 'ouvrir', title: 'Ouvrir Paramètres' },
    { id: 'apparence', title: 'Apparence' },
    { id: 'notifications', title: 'Notifications' },
    { id: 'auto', title: 'Automatisation' },
    { id: 'ops', title: 'Paramètres opérationnels' },
    { id: 'securite', title: 'Sécurité' },
    { id: 'sauver', title: 'Sauvegarder' },
  ],
  'workflow-complet': [
    { id: 'etape-1', title: '1. Le client dépose' },
    { id: 'etape-2', title: '2. Validation et mission' },
    { id: 'etape-3', title: '3. Dispatch' },
    { id: 'etape-4', title: '4. Enlèvement et transit' },
    { id: 'etape-5', title: '5. Livraison ou hub' },
    { id: 'etape-6', title: '6. Facturation et commission' },
  ],
}
